# fly.toml app configuration file generated for apitms on 2023-08-28T15:17:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apitms"
primary_region = "scl"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
